environment = "test"
aws_region = ""
project_name = "aws-account-iac-template-new"
org_name = "softkitit"
tf_state_file_name = "test-aws-account-iac-template-new-terraform.tfstate"
dynamo_db_table_name = "test-softkitit-aws-account-iac-template-new"
s3_bucket_name = "test-softkitit-aws-account-iac-template-new"
