name: Apply Terraform Changes

permissions:
  contents: read
  pull-requests: write
  id-token: write

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to apply changes to"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  apply_changes:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: softkitit/github-actions-terraform/.github/workflows/cd-apply-terraform-changes.yml@main
    with:
      environment: ${{ inputs.environment || 'dev' }}
    secrets: inherit