name: Terraform plan and format

permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  pull_request:
    branches:
      - main
    types: [ opened, reopened, synchronize ]

jobs:
  init_state:
    uses: softkitit/github-actions-terraform/.github/workflows/controller-initialize-terraform-state.yml@main
    with:
      organization: ${{ github.event.repository.owner.login }}
      project-name: ${{ github.event.repository.name }}-new
      environment: 'test'
    secrets: inherit

  plan_and_format:
    needs: init_state
    uses: softkitit/github-actions-terraform/.github/workflows/ci-terraform-plan-and-format.yaml@main
    with:
      environment: 'test'
      override-plan-comment: false
    secrets: inherit